modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/gizmo-ds/smsn-mod/issues"
license = "MIT"

[[mods]]
modId = "smsn"
version = "${version}"
displayName = "Save My Shit Network"
authors = "Gizmo"
description = '''
Block common mods from connecting to the internet without affecting the mods' functionality, preventing slow loading or game crashes caused by network issues.
'''
logoFile = "smsn-icon.png"
displayURL = "https://github.com/gizmo-ds/smsn-mod"

[[dependencies.smsn]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smsn]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smsn]]
modId = "cloth_config"
type = "optional"
versionRange = "[19.0.147,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "smsn.mixins.json"
