package dev.aika.smsn.mixin.forge;

import dev.aika.smsn.mixin.ModMixinInfo;
import dev.aika.smsn.mixin.ModMixinManager;

@SuppressWarnings({"unused", "SpellCheckingInspection"})
public class MixinPlatformImpl {
    public static void register() {
        ModMixinManager.addInfo(
                ModMixinInfo.create("ad_astra",
                        "dev.aika.smsn.forge.mixin.ad_astra.StationLoaderMixin"
                ),
                ModMixinInfo.create("additionalstructures",
                        "dev.aika.smsn.forge.mixin.additionalstructures.EventsMixin"
                ),
                ModMixinInfo.create("nitrogen",
                        "dev.aika.smsn.forge.mixin.aetherteam.UserData$ServerMixin"
                ),
                ModMixinInfo.create("alexscaves",
                        "dev.aika.smsn.forge.mixin.alex.AlexsCavesWebHelperMixin"
                ),
                ModMixinInfo.create("citadel",
                        "dev.aika.smsn.forge.mixin.alex.CitadelConstantsMixin",
                        "dev.aika.smsn.forge.mixin.alex.CitadelWebHelperMixin"
                ),
                ModMixinInfo.create("bagus_lib",
                        "dev.aika.smsn.forge.mixin.bagus_lib.TierHelperMixin"
                ),
                ModMixinInfo.create("blueprint",
                        "dev.aika.smsn.forge.mixin.blueprint.RewardHandlerMixin"
                ),
                ModMixinInfo.create("botania",
                        "dev.aika.smsn.forge.mixin.botania.ContributorListMixin"
                ),
                ModMixinInfo.create("tram_additions",
                        "dev.aika.smsn.forge.mixin.create_tram_additions.WorldTickMixin",
                        "dev.aika.smsn.forge.mixin.create_tram_additions.TramAdditionsMixin"
                ),
                ModMixinInfo.create("enigmaticlegacy",
                        "dev.aika.smsn.forge.mixin.enigmatic_legacy.DevotedBelieversHandlerMixin",
                        "dev.aika.smsn.forge.mixin.enigmatic_legacy.EnigmaticUpdateHandlerMixin"
                ),
                ModMixinInfo.create("exposure",
                        "dev.aika.smsn.forge.mixin.exposure.GildedMixin",
                        "dev.aika.smsn.forge.mixin.exposure.PatreonMixin"
                ),
                ModMixinInfo.create("hexerei",
                        "dev.aika.smsn.forge.mixin.hexerei.HexereiSupporterBenefitsMixin"
                ),
                ModMixinInfo.create("mru",
                        "dev.aika.smsn.forge.mixin.imb11.mru.APIMixin"
                ),
                ModMixinInfo.create("immersiveengineering",
                        "dev.aika.smsn.forge.mixin.immersive_engineering.ImmersiveEngineeringMixin"
                ),
                ModMixinInfo.create("immersivecaves",
                        "dev.aika.smsn.forge.mixin.immersivecaves.DiscordInviteOnJoinProcedureMixin"
                ),
                ModMixinInfo.create("inventoryprofilesnext",
                        "dev.aika.smsn.forge.mixin.ipn.IPNInfoManagerMixin"
                ),
                ModMixinInfo.create("obscure_api",
                        "dev.aika.smsn.forge.mixin.obscure.ObscuriaCollectionMixin",
                        "dev.aika.smsn.forge.mixin.obscure.ObscuriaCollectionMixin$Mod"
                ),
                ModMixinInfo.create("petrolpark",
                        "dev.aika.smsn.forge.mixin.petrolpark.BadgeHandlerMixin"
                ),
                ModMixinInfo.create("placebo",
                        "dev.aika.smsn.forge.mixin.placebo.TrailsManagerMixin",
                        "dev.aika.smsn.forge.mixin.placebo.WingsManagerMixin"
                ),
                ModMixinInfo.create("projecte",
                        "dev.aika.smsn.forge.mixin.projecte.ThreadCheckUUIDMixin"
                ),
                ModMixinInfo.create("quark",
                        "dev.aika.smsn.forge.mixin.quark.ThreadContributorListLoaderMixin",
                        "dev.aika.smsn.forge.mixin.quark.QButtonMixin"
                ),
                ModMixinInfo.create("ribbits",
                        "dev.aika.smsn.forge.mixin.ribbits.SupportersJSONMixin"
                ),
                ModMixinInfo.create("supplementaries",
                        "dev.aika.smsn.forge.mixin.supplementaries.CreditsMixin"
                ),
                ModMixinInfo.create("tenshilib",
                        "dev.aika.smsn.forge.mixin.tenshilib.PatreonDataManagerMixin"
                ),
                ModMixinInfo.create("titanium",
                        "dev.aika.smsn.forge.mixin.titanium.RewardMixin"
                ),
                ModMixinInfo.create("voidscape",
                        "dev.aika.smsn.forge.mixin.voidscape.DonatorHandlerMixin"
                ),
                ModMixinInfo.create("xaerominimap",
                        "dev.aika.smsn.forge.mixin.xaero.minimap.InternetMixin",
                        "dev.aika.smsn.forge.mixin.xaero.minimap.PatreonMixin"
                ),
                ModMixinInfo.create("xaeroworldmap",
                        "dev.aika.smsn.forge.mixin.xaero.world_map.InternetMixin",
                        "dev.aika.smsn.forge.mixin.xaero.world_map.PatreonMixin"
                )
        );
    }
}
