name: Publish

on:
  push:
    tags:
      - v*mc1.20.1
      - v*mc1.20.1-*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "1.20.1"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@093dfe9d598ec5a42246855d09b49dc76803c005
        with:
          arguments: build --no-daemon

      - name: Publishing
        run: ./gradlew publishUnified

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            forge/build/libs/*mc1.20.1.jar
            fabric/build/libs/*mc1.20.1.jar
